### ISSUE TITLE
C or C++?

### ISSUE THREAD

**Issue by livibetter** [qbradq/dnd1#1]
Those uses of `SEQ` macro for `case` ain't constant, I can only compile dnd1 as C++11 code.

On my system, CMake uses `gcc` (4.9.3) to compile.

**Comment by qbradq** [comment]
Hey, thanks for taking an interest in the project! I had inconsistencies with the SEQ macro myself. Apparently more recent versions of GCC have an extension that converts those statements to compile-time constants. I have updated that section of code to use a set of macros that use characters instead of a string. The CMakeLists.txt also now requires Clang. I should probably change it to prefer Clang instead of forcing it.

**Comment by qbradq** [comment]
Fixed in https://github.com/qbradq/dnd1/commit/1df22e10f376aa4ea47d092db50902dcfddf5ee5
